### PR TITLE
Fixed support section layout

### LINKED ISSUE #75: [Home page] Fix Support section layout
The Home page support section has minor layout issues as noted by graphics.
- Increase text padding on the mentor and volunteer pedestals
  - If possible, the pedestal elements should be abstracted to reduce repetition among the two
- Crop the statue images to prevent row wrapping until necessary
  - The statues currently have extra empty space causing the row to wrap prematurely
  - e.g. on a view width of 1024, the statues should still be on one row

### PR DESCRIPTION
**Pull request by RandyHuynh5815**
- Abstracted the pedestal elements into a new `StatuePedestal` component
- Increased text padding and made padding responsive
- Cropped statues svgs to prevent unnecessary row wrapping

TODOs:
- Ask graphics about padding

Resolves #75

### CODE REVIEW

**Review by rileysw — DISMISSED** [review]

File: src/views/home/sections/MentorsVolunteers/MentorsVolunteers.tsx [hunk 1]
```diff
@@ -1,75 +1,36 @@
...
+				statueImage={volunteerStatue}
+				statueAlt="HackUCI Volunteer Statue"
+				href="/volunteer"
+				buttonName="Volunteer Form"
+			>
+				Want a peek behind the scenes? Join our team of event volunteers that
+				make HackUCI run as smoothly as possible! Many roles are available and
+				shifts are flexible. Plus, get access to all the free food and all our
+				hackathon swag. We hope to see you on the team!
+			</StatuePedestal>
```
Comment (taesungh) [inline src/views/home/sections/MentorsVolunteers/MentorsVolunteers.tsx:33]: Suggestion: I think the abstraction is too coupled right now: the button could be specified as part of the children, not constrained to the pedestal.

File: src/assets/images/mentor_statue.svg [hunk 2]
```diff
@@ -1,4 +1,4 @@
-<svg width="500" height="273" viewBox="25 0 262 273" fill="none" xmlns="http://www.w3.org/2000/svg">
+<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 5.85 262 267.15">
```
Comment (rileysw) [inline src/assets/images/mentor_statue.svg:1]: Sorry I didn't catch this earlier @RandyHuynh5815 , the statue bases are now not centered on the pedestal (looks very awkward on mobile). I think we can expand viewbox width to 300 for the mentor statue and 320 for the volunteer statue and it'll still be small enough to not affect spacing.

**Review by rileysw — CHANGES_REQUESTED** [review]

File: src/assets/images/mentor_statue.svg (hunk 2 above)
Comment (taesungh) [reply src/assets/images/mentor_statue.svg]: @RandyHuynh5815, why did the SVG files double in size?

Comment (RandyHuynh5815) [reply src/assets/images/mentor_statue.svg]: I have modified the actual width of the images rather than the view box width by mistake. This issue should be resolved now.

**Review by rileysw — APPROVED** [review]

**Review by taesungh — APPROVED** [review]
Not sure how omitting the dimensions from the SVG will affect it, but looks fine to me.
